### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by ray1703** [destil/MoodSync#2]
i have a new sony android tv installed app but when you open it it says turned off on screen you click ok and says connecting to lifx then just closes app and don't connect

**Comment by destil** [comment]
Hi, I will work on the app today and resolve the crashes.

**Comment by ray1703** [comment]
Ok thanks can you let me know when it's done and ready for a update

**Comment by destil** [comment]
It's fixed and update is pushed to the Play Store.
